lab-2/config/routes.rb
Rails.application.routes.draw do
  get 'catalogue/httpartyGet'
  devise_for :users
  
  resources :sections
  
  # Naming a custom route for displaying /courses/(:id)
  resources :courses, except: [:show]
  get 'courses/:id', to: 'courses#decision'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"
  
  get 'user_list', to: 'user_list#show'
  #get 'catalog', to: 'courses#_form'

  resources :admin, only: [:index, :edit]
  resources :request, only: [:index]
  post "request/:id/update" => "request#update"
  post "admin/:id/update" => "admin#update"

  get 'error', to: 'error#show'
end

lab-2/app/views/admin/edit.html.erb
<div class="sub-admin-container">
	<div class="sub-admin-title">
		<h3>User Inform</h3>
	</div>
	<div class="row">
		<ul class="sub-admin-board-nav">
			<li class="col sub-admin-board-nav-email">Email</li>
			<li class="col sub-admin-board-nav-usertype">User Type</li>
			<li class="col sub-admin-board-nav-request">Request</li>
			<li class="col sub-admin-board-nav-edit">Back</li>
		</ul>
		<div class="col-9">
			<div class="sub-admin-board">
				<div class="col sub-admin-text-email">
					<%= @user.email %>
				</div>
				<div class="col sub-admin-text-usertype">
					<form action="update" method="post">
						<label for="user_type">User Type: </label>
						<select id="user_type" name="user_type">
							<option value="student">student</option>
							<option value="professor">professor</option>
							<option value="admin">admin</option>
						</select>
						<input type="submit" value="update">
					</form>
				</div>
				<div class="col sub-admin-text-request">
					<% if @user.request != "" && @user.request != nil%>
					Request: <%= @user.request %>
					<% else %>
					Request: none
					<% end %>
				</div>
				<div class="col sub-admin-text-edit">
					<%= link_to "back", :back %>
				</div>
			</div>
		</div>
	</div>
</div>

lab-2/app/views/admin/index.html.erb
<div class="sub-admin-container">
	<div class="sub-admin-title">
		<h3>Manage User Type</h3>
	</div>
	<div class="row">
		<ul class="sub-admin-board-nav">
			<li class="col sub-admin-board-nav-email">Email</li>
			<li class="col sub-admin-board-nav-usertype">User Type</li>
			<li class="col sub-admin-board-nav-request">Request</li>
			<li class="col sub-admin-board-nav-edit">Edit</li>
		</ul>
		<div class="col-9">
			
			<% @users.each do |user| %>
			<div class="sub-admin-board">
				<div class="col sub-admin-text-email">
					<%= user.email %>
				</div>
				<div class="col sub-admin-text-usertype">
					Role: <%= user.roles_name[0]%>
				</div>
				<div class="col sub-admin-text-request">
					<% if user.request != "" && user.request != nil%>
					Request: <%= user.request %>
					<% else %>
					Request: none
					<% end %>
				</div>
				<div class="col sub-admin-text-edit">
					<%= link_to 'edit', edit_admin_path(user.id)%>
				</div>
			</div>
			<% end%>
			
		</div>
	</div>
</div>