lab-3/config/routes.rb
Rails.application.routes.draw do
  resources :recommendations
  resources :grader_schedules
  resources :section_schedules
  devise_for :users
  
  resources :sections
  
  # Naming a custom route for displaying /courses/(:id)
  resources :courses, except: [:show]
  get 'courses/:id', to: 'courses#decision'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"

  #
  resources :grader_application
  post "grader_application/:id/update" => "grader_application#update"

  #
  resources :assigned_graders
  
  resources :admin, only: [:index, :edit]
  resources :request, only: [:index]
  post "request/:id/update" => "request#update"
  post "admin/:id/update" => "admin#update"
  #get '/admin/applications' => "admin#applications"
  
  #TODO: TEST THIS
  post "recommendations/:id" => "recommendations#destroy"

  #General error route that gets redirected to
  get 'error', to: 'error#show'
  
  #
  get 'notice', to: 'notice#show'
  
  #Grader application related
  get 'grader', to: 'grader#profile_show'
  get 'grader/app_edit', to: 'grader#app_show'
  put 'grader/app_edit', to: 'grader#app_submit'
  get 'grader/schedule_edit', to: 'grader#schedule_show'
  put 'grader/schedule_edit', to: 'grader#time_add'
  put 'grader/remove_time/:id', to: 'grader#time_delete'
  put 'grader/create_profile', to: 'grader#create_profile'
  
  #For editing the timeslots of a section
  get 'sections/:id/schedule_edit', to: 'section_schedules#index'
  post 'sections/:id/schedule_edit', to: 'section_schedules#create'
  put 'section_schedules/:id/delete', to: 'section_schedules#destroy'
  
  #Route for admin to assign graders
  get 'assign_graders', to: 'grader_application#needed_sections'
  get 'assign_graders/:section_id/select_grader', to: 'grader_application#eligible_graders'
  get 'assign_graders/:section_id/select_grader/:grader_id', to: 'grader_application#actual_assignment'

end

lab-3/app/models/section_schedule.rb
class SectionSchedule < ApplicationRecord
	belongs_to :section
end

lab-3/app/controllers/section_schedules_controller.rb
class SectionSchedulesController < ApplicationController
  before_action :set_section_schedule, only: %i[ show edit update ]

  # From route 'sections/:id/schedule_edit'
  def index
    
    @section = Section.find(params[:id])
    @section_schedules = @section.section_schedules
  end

  # GET /section_schedules/1 or /section_schedules/1.json
  def show
  end

  # GET /section_schedules/new
  def new
    @section_schedule = SectionSchedule.new
  end

  # GET /section_schedules/1/edit
  def edit
  end

  # Called when admin is on /sections/:section_id/schedule_edit page, then submits a new time to add
  def create
    
    section = Section.find(params[:id])
    @section_schedule = SectionSchedule.create(section_id: section.id, startTime: Time.parse(params[:startTime]), endTime: Time.parse(params[:endTime]), weekday: params[:weekday])

    redirect_to '/sections/' + section.id.to_s + '/schedule_edit', notice: "Section schedule was successfully created."
    
  end

  # PATCH/PUT /section_schedules/1 or /section_schedules/1.json
  def update
    respond_to do |format|
      if @section_schedule.update(section_schedule_params)
        format.html { redirect_to section_schedule_url(@section_schedule), notice: "Section schedule was successfully updated." }
        format.json { render :show, status: :ok, location: @section_schedule }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @section_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /section_schedules/1 or /section_schedules/1.json
  def destroy
    @section_schedule = SectionSchedule.find(params[:id])
    @original_section = @section_schedule.section
    @section_schedule.destroy

    respond_to do |format|
      format.html { redirect_to '/sections/' + @original_section.id.to_s + '/schedule_edit', notice: "Section schedule was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section_schedule
      @section_schedule = SectionSchedule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def section_schedule_params
      params.require(:section_schedule).permit(:weekday, :startTime, :endTime)
    end
end

lab-3/app/helpers/section_schedules_helper.rb
module SectionSchedulesHelper
	
end

lab-3/app/views/section_schedules/_form.html.erb
<%= form_with(model: @section_schedule) do |form| %>
	
<div class = "sub-section-edit-all">
  <div class="field">
    
	<%= form.label :weekday, "Day" %>
	<%= form.select :weekday, ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], include_blank: true %>
  </div>

  <div class="field">
    	<%= form.label 'Start Time' %>
    	<%= form.time_field :startTime, value: '%l:%M %p' %>
  </div>

  <div class="field">
    	<%= form.label 'End Time' %>
    	<%= form.time_field :endTime, value: '%l:%M %p' %>
  </div>

  <div class="actions">
    	<%= form.submit "Add Time" %>
  </div>
  
</div>
<% end %>

lab-3/app/views/section_schedules/edit.html.erb
<h1>Editing Section Schedule</h1>

<%= render 'index', section_schedule: @section.section_schedule %>

<%= render 'form', section_schedule: @section.section_schedule %>

<%= link_to 'Show', @section_schedule %> |
<%= link_to 'Back', section_schedules_path %>

lab-3/app/views/section_schedules/index.html.erb
<div id="main-container">
<div id="class-list">

<p id="notice"><%= notice %></p>

<h3><%= 'Editing Schedule for Section of CSE ' + @section.course.courseNumber.to_s %></h3>

<br>
Delete section times or add new ones here.
<br><br>

<table>
  <thead>
    <tr>
      <th>Weekday</th>
      <th>Start</th>
      <th>End</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @section_schedules.each do |section_schedule| %>
      <tr>
        <td><%= section_schedule.weekday %></td>
        <td><%= prettyTime(section_schedule.startTime) %></td>
        <td><%= prettyTime(section_schedule.endTime) %></td>
        <td><%= button_to 'Destroy', '/section_schedules/' + section_schedule.id.to_s + '/delete', method: :put %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
Use the form below to add a new time to this section's schedule.
<br>

<%= render 'form' %>

<br>

<%= link_to 'Return to Section', '/sections/' + @section.id.to_s %>
<%= link_to 'Return to Parent Course', '/courses/' + @section.course_id.to_s %>
<%= link_to 'Link to edit other section details', '/sections/' + @section.id.to_s + '/edit' %>

</div>
</div>

lab-3/app/views/section_schedules/new.html.erb
<h1>New Section Schedule</h1>

<%= render 'form', section_schedule: @section_schedule %>

<%= link_to 'Back', section_schedules_path %>

lab-3/app/views/section_schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weekday:</strong>
  <%= @section_schedule.weekday %>
</p>

<p>
  <strong>Start:</strong>
  <%= prettyTime(Time.at(@section_schedule.startTime)) %>
</p>

<p>
  <strong>End:</strong>
  <%= prettyTime(Time.at(@section_schedule.endTime)) %>
</p>

<%= link_to 'Edit', edit_section_schedule_path(@section_schedule) %> |
<%= link_to 'Back', section_schedules_path %>

lab-3/app/views/section_schedules/test.html.erb
<!-- The part of the edit page where we can add a new time to the schedule -->
Add a new time to your available grading schedule here.
<%= form_with url: '/grader/schedule_edit', method: :put do |form| %>
	
	<div class="field">
	<div class = "sub-section-edit-all">
	<%= form.label :weekday, "Day" %>
	<%= form.select :weekday, ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], include_blank: true %>
	
	<%= form.label :start_hour, "Start Hour" %>
	<%= form.text_field :start_hour, size: 1 %>
	<%= form.label :start_minute, "Start Minute" %>
	<%= form.text_field :start_minute, size: 1 %>
	<%= form.select :start_period, ["am", "pm"], include_blank: true %>
	
	<%= form.label :end_hour, "End Hour" %>
	<%= form.text_field :end_hour, size: 1 %>
	<%= form.label :end_minute, "End Minute" %>
	<%= form.text_field :end_minute, size: 1 %>
	<%= form.select :end_period, ["am", "pm"], include_blank: true %>
	
	</div>
	</div>
	<br>
	
	<div class="field">
	<div class = "sub-section-edit-all">
	<%= form.submit "Add Time" %>
	</div>
	</div>

<% end %>