lab-3/config/routes.rb
Rails.application.routes.draw do
  resources :recommendations
  resources :grader_schedules
  resources :section_schedules
  devise_for :users
  
  resources :sections
  
  # Naming a custom route for displaying /courses/(:id)
  resources :courses, except: [:show]
  get 'courses/:id', to: 'courses#decision'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"

  #
  resources :grader_application
  post "grader_application/:id/update" => "grader_application#update"

  #
  resources :assigned_graders
  
  resources :admin, only: [:index, :edit]
  resources :request, only: [:index]
  post "request/:id/update" => "request#update"
  post "admin/:id/update" => "admin#update"
  #get '/admin/applications' => "admin#applications"
  
  #TODO: TEST THIS
  post "recommendations/:id" => "recommendations#destroy"

  #General error route that gets redirected to
  get 'error', to: 'error#show'
  
  #
  get 'notice', to: 'notice#show'
  
  #Grader application related
  get 'grader', to: 'grader#profile_show'
  get 'grader/app_edit', to: 'grader#app_show'
  put 'grader/app_edit', to: 'grader#app_submit'
  get 'grader/schedule_edit', to: 'grader#schedule_show'
  put 'grader/schedule_edit', to: 'grader#time_add'
  put 'grader/remove_time/:id', to: 'grader#time_delete'
  put 'grader/create_profile', to: 'grader#create_profile'
  
  #For editing the timeslots of a section
  get 'sections/:id/schedule_edit', to: 'section_schedules#index'
  post 'sections/:id/schedule_edit', to: 'section_schedules#create'
  put 'section_schedules/:id/delete', to: 'section_schedules#destroy'
  
  #Route for admin to assign graders
  get 'assign_graders', to: 'grader_application#needed_sections'
  get 'assign_graders/:section_id/select_grader', to: 'grader_application#eligible_graders'
  get 'assign_graders/:section_id/select_grader/:grader_id', to: 'grader_application#actual_assignment'

end

lab-3/app/controllers/grader_application_controller.rb
class GraderApplicationController < ApplicationController
	
=begin
	GraderApplication controller handles routes and functions related to
	the *admin* view of graders, graders' applications, and assigning them to sections.
=end
	
	#Required to allow user forms to display (CanCanCan, Rolify gems)
	skip_before_action :verify_authenticity_token
	
	#Course-related pages are restricted to registered users only.
	#Some features are exclusive to admins
	#These functions redirect users to a descriptive error page.
    	before_action :checkLogin
    	before_action :checkAdmin

	private def checkLogin
		unless user_signed_in?
			flash[:user_error] = 'You must sign in to check if you have access to this feature.'
			redirect_to '/error'
		end
	end

	private def checkAdmin
		unless current_user.has_any_role? :admin
			flash[:user_error] = 'You do not have proper permissions to access this feature.'
			redirect_to '/error'
			return false
		else
			return true
		end
	end

	def index
		@graders =Grader.all
	end
	
	#Borrowed from app_show controller function/view in Grader controller
	def show
		@grader = Grader.find(params[:id])
		@resume = @grader.resume
		@interest = @grader.currently_interested
		@interests = @grader.interested_courses
		@qualifications = @grader.qualified_courses
		
		@mondays = GraderAvailability.where(["grader_id = ? and weekday = ?", @grader.id, "Monday"]).order(:start)
		@tuesdays = GraderAvailability.where(["grader_id = ? and weekday = ?", @grader.id, "Tuesday"]).order(:start)
		@wednesdays = GraderAvailability.where(["grader_id = ? and weekday = ?", @grader.id, "Wednesday"]).order(:start)
		@thursdays = GraderAvailability.where(["grader_id = ? and weekday = ?", @grader.id, "Thursday"]).order(:start)
		@fridays = GraderAvailability.where(["grader_id = ? and weekday = ?", @grader.id, "Friday"]).order(:start)
	end

	def edit
		@grader = Grader.find([params[:id]])
		@courses = Course.all
		@grader_assignments = GraderAssignment.new
	end
	
	def update
		@grader = Grader.find_by id: params[:id]
		@grader_assignment = GraderAssignment.new
		@grader_assignment.grader_id = @grader.id
		@grader_assignment.section_id =  params[:section_id]
		@grader_assignment.save
		flash[:notice] = 'Grader successfully signed in to section'
		redirect_to '/notice'
	end
	
=begin
#TODO: review legacy code above
=end
	
	# From route '/assign_graders' - displays sections still in need of graders
	def needed_sections
		sections = Section.all
		
		# needing_graders array will store only sections that still need graders
		# We filter by iterating over each section, below
		
		@needing_graders = []
		sections.each do |section|
			difference = section.numGradersNeeded - section.grader_assignments.length
			
			if difference > 0
				@needing_graders.push section
			end
		end
		
		render 'assign_graders'
	end
	
	# From route '/assign_graders/:section_id/select_grader'
	# where admin initially selected a section, and now must select a grader
	def eligible_graders
		@section = Section.find(params[:section_id])
		
		# Filter out only grader profiles that have shown interested in grading this semester
		totalPool = Grader.where(["currently_interested = ?", true])
		@graders = []
		
		# Then, further filter to graders that have not already been assigned up this section
		totalPool.each do |grader|
			caughtDupe = 0
			assignments = grader.grader_assignments
			
			assignments.each do |assignment|
				if assignment.section_id == @section.id
					caughtDupe = 1
				end
			end
			
			if caughtDupe == 0
				@graders.push grader
			end
		end
		
	end
	
	# From route '/assign_graders/:section_id/select_grader/'
	# where admin initially selected a section then selected a grader
	# Redirects them to the page containing the list of current grader assignments
	def actual_assignment
		GraderAssignment.create section_id: params[:section_id], grader_id: params[:grader_id]
		#TODO: ADD CONTROL CODE FOR DUPES
		redirect_to '/assigned_graders'
	end











	
	
	
	
	

end

lab-3/app/helpers/grader_application_helper.rb
module GraderApplicationHelper
end

lab-3/app/views/grader_application/_section_list_for_assignment.html.erb
<% @needing_graders.each do |section| %>
<div class="sub-section-board">
  <div class="col sub-section-course-name">
	  <%= 'CSE ' + section.course.courseNumber.to_s %>
	  <br>
	  <%= section.course.courseName %>
  </div>
  <div class="col sub-section-section-instructor">
    <% if section.instructor? %>
    <%= section.instructor %>
    <% else %>
      -
    <% end %>
    <br>
    <% if section.instructorEmail? %>
    <%= section.instructorEmail %>
    <% else %>
      -
    <%end%>
  </div>
  <div class="col sub-section-section-buliding">
    <%if section.buildingAndRoom? %>
      <%= section.buildingAndRoom %>
    <% else %>
      -
    <% end %>
  </div>
  <div class="col sub-section-section-graders-need">
    <%= section.grader_assignments.length %>
  </div>
  <div class="col sub-section-section-graders-need">
    <%= section.numGradersNeeded %>
  </div>
  <div class= "col sub-section-section-schedule">
    <%if section.term? %>
    <%= section.term %>
    <% else %>
      -
    <% end %>
    <br>
    <% if !section.section_schedules.empty? %>
    <% section.section_schedules.each do |section_schedule|%>
      <p>
        <%= section_schedule.weekday + ": " + prettyTime(Time.at(section_schedule.startTime)) + " to " + prettyTime(Time.at(section_schedule.endTime))%>
      </p>
    <% end %>
    <% else %>
      <p> No Schedule </p>
    <% end %>
  </div>
  <div class="col sub-section-section-edit">
    <p><%= link_to 'View Section', section %></p>
    <p><%= link_to 'Assign Grader', '/assign_graders/' + section.id.to_s + '/select_grader' %></p>
  </div>
</div>
<% end %>

lab-3/app/views/grader_application/assign_graders.html.erb
<div class="sub-course-show-container-two">
  <div class="sub-course-title">
    <h3>Sections in Need of Graders</h3>
  </div>
  
  <div id="pretext">
  You can also view the list of current grader assignments here: 
  <%= link_to 'Assigned Graders', '/assigned_graders' %>
  </div> <br>
  
  <div class="row">
    <ul class="sub-section-board-nav">
      <li class="col sub-section-board-nav-course-name">Course Name</li>
      <li class="col sub-section-board-nav-section-instructor">Instructor</li>
      <li class="col sub-section-board-nav-section-buliding">Location</li>
      <li class="col sub-section-board-nav-section-graders-need">Graders Assigned</li>
      <li class="col sub-section-board-nav-section-graders-need">Total Graders Needed</li>
      <li class="col sub-section-board-nav-section-section-schedule">Schedule</li>
      <li class="col sub-section-board-nav-section-edit">Show</li>
    </ul>
  </div>
	<%= render 'section_list_for_assignment' %>
</div>

lab-3/app/views/grader_application/edit.html.erb
<div class="sub-application-container">
  <div class="sub-application-title">
    <h3>Courses</h3>
  </div>
  <div class="row">
    <ul class="sub-application-board-nav">
      <li class="col sub-application-board-nav-email">Course Number</li>
      <li class="col sub-application-board-nav-qualification">Course Name</li>
      <li class="col sub-application-board-nav-interest">Section</li>
      <li class="col sub-application-board-nav-recommendation">Schedules</li>
      <li class="col sub-application-board-nav-info">Student Info</li>
    </ul>
    <div class="col-9">

      <% @courses.each do |course| %>
      <% if course.sections.any? %>
      <% x = 0 %> <% y = 0 %>
      <% while x < course.sections.length %>
      <div class="sub-application-board">
        <div class="col sub-application-text-email">
          CSE <%= course.courseNumber %>
        </div>
        <div class="col sub-application-text-qualification">
          <%= course.courseName %>
        </div>
        <div class="col sub-application-text-interest">
          <%= course.sections[x].sectionNumber %>
        </div>
        <div class="col sub-application-text-recommendation">
          <% if course.sections[x].section_schedules.any? %>
          <% while y < course.sections[x].section_schedules.length %>
          <%= course.sections[x].section_schedules[y].weekday + ": " + prettyTime(Time.at(course.sections[x].section_schedules[y].startTime)) + " to " + prettyTime(Time.at(course.sections[x].section_schedules[y].endTime))%>
          <% y = y + 1 %>
          <% end %>
          <% y = 0 %>
          <% else %>
          <%= "no schedule" %>
          <% end %>
        </div>
        <div class="col sub-application-text-info">
          <form action="update" method="post">
            <select id="section_id" name="section_id" style="display: none;">
              <option value="<%= course.sections[x].id%>"><%= course.sections[x].id%></option>
            </select>
            <input type="submit" value="update">
          </form>
        </div>
        <% x = x+1 %>
      </div>
      <% end%>
      <% end%>
      <% end%>
      
    </div>
    	<br>
	</div>

lab-3/app/views/grader_application/eligible_graders.html.erb
<div class="sub-course-show-container-two">
  <div class="sub-course-title">
    <h3>Select a Grader for this Section of CSE <%= @section.course.courseNumber %></h3>
  </div>
  
  <div id="pretext">
  You can also view the list of current grader assignments here: 
  <%= link_to 'Assigned Graders', '/assigned_graders' %>
  <br>
  <%= link_to 'Back to Course Select', '/assign_graders' %>
  </div> 
  <br>
  
  <div class="row">
    <ul class="sub-application-board-nav">
	<li class="col sub-application-board-nav-email">Email</li>
	<li class="col sub-application-board-nav-qualification">Qualifications</li>
	<li class="col sub-application-board-nav-interest">Interests</li>
	<li class="col sub-application-board-nav-recommendation">Has Recommendation?</li>
	<li class="col sub-application-board-nav-info">Student Info</li>
    </ul>
    <div class="col-9">
			
		<% @graders.each do |grader| %>
			<div class="sub-application-board">
				<div class="col sub-application-text-email">
					<%if grader.user.first_name? && grader.user.last_name? %>
    					<%= grader.user.first_name + ' ' + grader.user.last_name %>
    					<% else %>
    					-
    					<% end %>
					<br>
					<%= grader.user.email %>
				</div>
				<div class="col sub-application-text-qualification">
					<% if grader.qualified_courses.empty? %>
					<%= "empty" %>
					<% else %>
					<%= grader.qualified_courses %>	
					<% end %>
				</div>
				<div class="col sub-application-text-interest">
					<% if grader.interested_courses.empty? %>
					<%= "empty" %>
					<% else %>
					<%= grader.interested_courses %>
					<% end  %>
				</div>
				<div class="col sub-application-text-recommendation">
					<!-- Print links to each recommendation, if the student has been written a recommendation -->
					<% reccs = Recommendation.where(["email = ?", grader.user.email]) %>
					<% if reccs.length > 0 %>
						<%= "Yes" %>
						<% reccs.each do |recommendation| %>
							<%= link_to 'Link', '/recommendations/' + recommendation.id.to_s %>
						<% end %>
					<% else %>
					<%= "No" %>
					<% end %>
				</div>
				<div class="col sub-application-text-info">
					<%= link_to 'View profile', grader_application_path(grader) %>
					<%= link_to 'Assign to section', '/assign_graders/' + @section.id.to_s + '/select_grader/' + grader.id.to_s %>
				</div>
			</div>
		<% end %>
			
	</div>
    
  </div>
	
</div>

lab-3/app/views/grader_application/index.html.erb
<div class="sub-application-container">
	<div class="sub-application-title">
		<h3>Grader applications</h3>
	</div>
	<div class="row">
		<ul class="sub-application-board-nav">
			<li class="col sub-application-board-nav-email">Email</li>
			<li class="col sub-application-board-nav-qualification">Qualifications</li>
			<li class="col sub-application-board-nav-interest">Interests</li>
			<li class="col sub-application-board-nav-recommendation">Recommendation</li>
			<li class="col sub-application-board-nav-info">Student Info</li>
		</ul>
		<div class="col-9">
			
			<% @graders.each do |grader| %>
			<div class="sub-application-board">
				<div class="col sub-application-text-email">
					<%= grader.user.email %>
				</div>
				<div class="col sub-application-text-qualification">
					<% if grader.qualified_courses.empty? %>
					<%= "empty" %>
					<% else %>
					<%= grader.qualified_courses %>	
					<% end %>
				</div>
				<div class="col sub-application-text-interest">
					<% if grader.interested_courses.empty? %>
					<%= "empty" %>
					<% else %>
					<%= grader.interested_courses %>
					<% end  %>
				</div>
				<div class="col sub-application-text-recommendation">
					<% if Recommendation.find_by(email: grader.user.email) != nil %>
					<%= "Recommendation exist" %>
					<a href="/recommendations">Link</a>
					<% else %>
					<%= "No recommendation" %>
					<% end %>
				</div>
				<div class="col sub-application-text-info">
					<%= link_to 'Info', grader_application_path(grader) %>
					<%= link_to 'Add to section', edit_grader_application_path(grader) %>
				</div>
			</div>
			<% end%>
			
		</div>
		<%= link_to 'Assigned graders page', assigned_graders_path %>
	</div>
</div>

lab-3/app/views/grader_application/show.html.erb
<div class="sub-admin-container">
	<div class="sub-admin-title">
		<h3>
		Profile for 
		<%= @grader.user.email  %>
		</h3>
	</div>
	<div class="row">
		<ul class="sub-admin-board-nav">
			<li class="col sub-admin-board-nav-email">Email</li>
			<li class="col sub-admin-board-nav-usertype">Name</li>
			<li class="col sub-admin-board-nav-request">Contact Info</li>
			
		</ul>
		<div class="col-9">
			
			
			<div class="sub-admin-board">
				<div class="col sub-admin-text-email">
					<%= @grader.user.email %>
				</div>
				<div class="col sub-admin-text-usertype">
					<% if @grader.user.first_name.nil? && @grader.user.last_name.nil? %>
					<%= "-" %>
					<% else %>
					<%= @grader.user.first_name %>
					<%= @grader.user.last_name %>
					<% end %>
				</div>
				<div class="col sub-admin-text-request">
					<% if @grader.user.phone_number.nil? %>
					<%= "-" %>
					<% else %>
					<%= @grader.user.phone_number %>
					<% end %>
				</div>
				
			</div>
			
		</div>
	</div>

<div class="sub-admin-title">
<br>
<%= 'Interest in grading this semester: ' + @interest.to_s %>
<br><br>

<h3>Completed Courses: </h3>
<%= @qualifications %>
<br><br>
<h3>Interested Courses: </h3>
<%= @interests %>
<br><br>

<h3>Additional Experience: </h3>
<%= @resume %>
<br>

<br><br><br>

<h3>Available Schedule Times:</h3>
<br>

<!-- Create Monday list only if it exists -->
<% if @mondays.length > 0 %>
	<h3>Monday</h3>
	<% @mondays.each do |period| %>
		
		<!-- locals hash needed to pass |period| into the weekday_time_display partial -->
		<%= render partial: "grader/weekday_time_display", locals: {period: period} %>
		
	<% end %>
	
<% end %>

<!-- Do the same for lists of every other day -->
<% if @tuesdays.length > 0 %>
	<h3>Tuesday</h3>
	<% @tuesdays.each do |period| %>
		<%= render partial: "grader/weekday_time_display", locals: {period: period} %>
	<% end %>
<% end %>

<% if @wednesdays.length > 0 %>
	<h3>Wednesday</h3>
	<% @wednesdays.each do |period| %>
		<%= render partial: "grader/weekday_time_display", locals: {period: period} %>
	<% end %>
<% end %>

<% if @thursdays.length > 0 %>
	<h3>Thursday</h3>
	<% @thursdays.each do |period| %>
		<%= render partial: "grader/weekday_time_display", locals: {period: period} %>
	<% end %>
<% end %>

<% if @fridays.length > 0 %>
	<h3>Friday</h3>
	<% @fridays.each do |period| %>
		<%= render partial: "grader/weekday_time_display", locals: {period: period} %>
	<% end %>
<% end %>

</div>
</div>