lab-3/config/routes.rb
Rails.application.routes.draw do
  resources :recommendations
  resources :grader_schedules
  resources :section_schedules
  devise_for :users
  
  resources :sections
  
  # Naming a custom route for displaying /courses/(:id)
  resources :courses, except: [:show]
  get 'courses/:id', to: 'courses#decision'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"

  #
  resources :grader_application
  post "grader_application/:id/update" => "grader_application#update"

  #
  resources :assigned_graders
  
  resources :admin, only: [:index, :edit]
  resources :request, only: [:index]
  post "request/:id/update" => "request#update"
  post "admin/:id/update" => "admin#update"
  #get '/admin/applications' => "admin#applications"
  
  #TODO: TEST THIS
  post "recommendations/:id" => "recommendations#destroy"

  #General error route that gets redirected to
  get 'error', to: 'error#show'
  
  #
  get 'notice', to: 'notice#show'
  
  #Grader application related
  get 'grader', to: 'grader#profile_show'
  get 'grader/app_edit', to: 'grader#app_show'
  put 'grader/app_edit', to: 'grader#app_submit'
  get 'grader/schedule_edit', to: 'grader#schedule_show'
  put 'grader/schedule_edit', to: 'grader#time_add'
  put 'grader/remove_time/:id', to: 'grader#time_delete'
  put 'grader/create_profile', to: 'grader#create_profile'
  
  #For editing the timeslots of a section
  get 'sections/:id/schedule_edit', to: 'section_schedules#index'
  post 'sections/:id/schedule_edit', to: 'section_schedules#create'
  put 'section_schedules/:id/delete', to: 'section_schedules#destroy'
  
  #Route for admin to assign graders
  get 'assign_graders', to: 'grader_application#needed_sections'
  get 'assign_graders/:section_id/select_grader', to: 'grader_application#eligible_graders'
  get 'assign_graders/:section_id/select_grader/:grader_id', to: 'grader_application#actual_assignment'

end

lab-3/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	#Course controller handles everything related to displaying and altering course info
	
	include HTTParty  #for httpartyGet function
  
	
	#Course-related pages are restricted to registered users only.
	#Some features are exclusive to admins
	#These functions redirect users to a descriptive error page.
    	before_action :checkLogin
    	before_action :checkAdmin, only: [ :new, :edit, :create, :update, :destroy ]
	
	#Allows these methods access to the course of interest
	before_action :set_course, only: [ :edit, :update, :destroy ]

private def checkLogin
	unless user_signed_in?
		flash[:user_error] = 'You must sign in to check if you have access to this feature.'
		redirect_to '/error'
	end
end

private def checkAdmin
	unless current_user.has_any_role? :admin
		flash[:user_error] = 'You do not have proper permissions to access this feature.'
		redirect_to '/error'
		return false
	else
		#double check this line
		return true
	end
end

# GET /courses or /courses.json (display full list of courses)
def index
	@courses = filter(Course.all)
end

# Any /courses/(value) route calls upon this function - handles both /courses/reload and 
# /courses/(course_id)
def decision
	#decision for id and reload
	if params[:id].to_i > 0  # /courses/(course_id)
		@course = set_course
		show
	elsif (params[:id] == "reload") && current_user.has_any_role?(:admin)  # /courses/reload, requires admin role
		reload
	elsif (params[:id] == "reload") && !current_user.has_any_role?(:admin) # throw error if not an admin...
		flash[:user_error] = 'You do not have proper permissions to access this feature.'
		#fix double render
		redirect_to '/error'
	end 
end

# GET /courses/1 or /courses/1.json (display the details for a single course, and its sections) - depends upon decision function, defined above
def show
  	# Needed for the "Add a Section" link
  	@course_id = @course.id
  	# Needed to display list of sections
  	@sections = @course.sections
  	render :show
end

# GET /courses/new
def new
	@course = Course.new
end

# GET /courses/1/edit
def edit
	
end

# POST /courses or /courses.json
def create
	@course = Course.new(course_params)

    	respond_to do |format|
      		if @course.save
        		format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        		format.json { render :show, status: :created, location: @course }
      		else
        		format.html { render :new, status: :unprocessable_entity }
        		format.json { render json: @course.errors, status: :unprocessable_entity }
      		end
    	end
end

# PATCH/PUT /courses/1 or /courses/1.json
def update
    	respond_to do |format|
      		if @course.update(course_params)
        		format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        		format.json { render :show, status: :ok, location: @course }
      		else
        		format.html { render :edit, status: :unprocessable_entity }
        		format.json { render json: @course.errors, status: :unprocessable_entity }
      		end
    	end
end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    
    sections = @course.sections
    sections.destroy_all
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  #Sets what filter categories are allowed and gets them from the url
  def filter_params
    params.fetch(:filter, {}).permit(:courseNumber, :courseName, :inClassGraders)
  end

  #Sanitizes parameter input and runs sql query
  def filter(relation)
    v = filter_params
    v.compact_blank!
    return relation unless v.present?
      relation.where(v)
    end
  end
  
  #Runs when the 'courses/reload' route is accessed. Exclusive to Admins. 
  def reload
    #Wipes entire course/section database
    oldSections = Section.all
    oldSections.destroy_all
    oldCourses = Course.all
    oldCourses.destroy_all
    
    #Retrieves data anew from OSU website
    courses = httpartyGet
    parseCourses(courses)
    
    #Refreshes course page
    redirect_to '/courses'
  end
  
  #Retrieves course catalog information from OSU as JSON, and converts it into a Ruby array containing both section and course information
  private def httpartyGet
    url="https://content.osu.edu/v2/classes/search?q=cse&campus=col&term=1224&p=1&subject=cse&academic-career=ugrd"
    response=HTTParty.get(url)
    #response.body is the HTTP response body in string format. 
    #in this case it contains the JSON file
    #converts that string to a hash
    r_hash = JSON.parse(response.body)

    #the commented out line of code writes the json file to a file
    #copy and paste this file into https://jsonformatter.curiousconcept.com/# to get an interactive JSON
    File.open('myfile', 'w'){|file|file.write(response.body)}

    #Formatting the body of the HTTP response to access the data we'll need
    r_array = r_hash.to_a[0]
    data=r_array[1].to_a
    #Crop the array down to just the courses and sections information
    data.shift(11)
    #more formatting
    courses=data[0][1]
  end  

#Converts an array containing courses with nested course and sections hashes
  #Into model objects that can be added to the database; a partial JSON file. 
  #Meant to take the return from httpartyGet
  def parseCourses(courses)
    courses.each do |course|
      check = course['course']
      course_courseNumber = course['course']['catalogNumber']
      course_courseName = course['course']['title']
      course_term = course['course']['term']
      existing_course = Course.find_by(courseNumber: course_courseNumber)
      course_object = existing_course || Course.create(courseNumber: course_courseNumber, courseName: course_courseName)
      sections = course['sections']
      sections.each do |section|
        section_sectionNumber = section['section']
        section_buildingAndRoom = section['meetings'][0]['buildingDescription']
        section_instructor = section['meetings'][0]['instructors'][0]['displayName']
        section_instructorEmail = section['meetings'][0]['instructors'][0]['email']
        @section_object = Section.create(sectionNumber: section_sectionNumber, 
          course_id: course_object.id, 
          buildingAndRoom: section_buildingAndRoom, 
          instructor: section_instructor, 
          term: course_term, 
          instructorEmail: section_instructorEmail)
        meetings = section['meetings']
        meetings.each do |meeting|
          date = meeting['startDate']
          startTime_str = meeting['startTime']
          weekday_arr = findWeekdays(meeting)
          weekday_arr.each do |day|
            startTime = Time.parse(startTime_str)
            endTime_str = meeting['endTime']
            endTime = Time.parse(endTime_str)
            @schedule_object = SectionSchedule.create(weekday: day, 
              startTime: startTime, 
              endTime: endTime, 
              section_id: @section_object.id)
          end
        end
      end
    end
  end
  
  #converst string of time into seconds since midnight, based on a date. 
  private def parseTime(str, date)
    time = Time.parse(str)
    start = Date.parse(date)
    start = Time.new(start.year, start.month, start.mday)
    time = start-time
  end

  private def findWeekdays(meeting)
    a = []
    a << 'Monday' if meeting['monday']
    a << 'Tuesday' if meeting['tuesday']
    a << 'Wednesday' if meeting['wednesday']
    a << 'Thursday' if meeting['thursday']
    a << 'Friday' if meeting['friday']
    a << 'Saturday' if meeting['saturday']
    a << 'Sunday' if meeting['sunday']
    a
  end

  # Use callbacks to share common setup or constraints between actions.
  private def set_course
    @course = Course.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  private def course_params
    params.require(:course).permit(:courseNumber, :courseName, :inClassGraders)
  end

lab-3/app/helpers/courses_helper.rb
module CoursesHelper

end

lab-3/app/views/courses/_filterC.erb
<%= form_for(createFormObjFromParam(:filter), 
              method: :get, 
              url: courses_path, 
              html: {class: 'form'}) do |f| %>

  <div class="form-group">
    <%= f.label(:courseNumber, class: 'control-label') %>
    <%= f.select :courseNumber, Course.distinct.pluck(:courseNumber).sort!.unshift('') %>
  </div>

  <div class="form-group">
    <%= f.label(:inClassGraders)%>
    <%= f.select :inClassGraders, ['', 'true', 'false'] %>
  </div>

  <div class="text-right">
    <%= content_tag(:button,
                    'Search',
                    type: 'submit',
                    class: 'btn btn-info') %>
  </div>

<% end %>
<div class="clear-filters">
  <%= button_to "Clear", courses_path, method: :get %>
</div>

lab-3/app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class = "sub-course-edit-all">
    <%= form.label :courseNumber, "Course Number (should be the # in \"CSE #\")" %>
    <%= form.number_field :courseNumber %>
    </div>
  </div>
  <div class="field">
    <div class = "sub-course-edit-all">
    <%= form.label :courseName, "Course Name" %>
    <%= form.text_field :courseName %>
    </div>
  </div>

  <div class="field">
    <div class = "sub-course-edit-all">
    <%= form.label :inClassGraders, "Needs In Class Graders?" %>
    <%= form.check_box :inClassGraders %>
    </div>
  </div>

  <div class="actions">
    <div class = "sub-course-edit-all">
    <%= form.submit %>
    </div>
  </div>
<% end %>

lab-3/app/views/courses/_s_schedule_list.erb
<% @section_schedules.each do |schedule| %>
<p>
  <%= section_schedule.weekday + ": " + prettyTime(Time.at(section_schedule.startTime)) + " to " + prettyTime(Time.at(section_schedule.endTime))%>
</p>

<%= link_to 'Edit Schedule', edit_section_schedule_path(@section_schedule) %> |
<% end %>

lab-3/app/views/courses/_section_list.html.erb
<% @sections.each do |section| %>
<div class="sub-section-board">
  <div class="col sub-section-section-number">
	  <%= section.sectionNumber %>
  </div>
  <div class="col sub-section-section-instructor">
    <% if section.instructor? %>
    <%= section.instructor %>
    <% else %>
      -
    <% end %>
    <br>
    <% if section.instructorEmail? %>
      <%= section.instructorEmail %>
    <% else %>
      -
    <% end %>
  </div>
  <div class="col sub-section-section-buliding">
    <% if section.buildingAndRoom? %>
      <%= section.buildingAndRoom %>
    <% else %>
      -
    <% end %>
  </div>
  <div class="col sub-section-section-graders-need">
    <%= section.grader_assignments.length %>
  </div>
  <div class="col sub-section-section-graders-need">
    <%= section.numGradersNeeded %>
  </div>
  <div class= "col sub-section-section-schedule">
    <% if section.term? %>
      <%= section.term %>
    <% else %>
      -
    <% end %>
    <br>
    <% if !section.section_schedules.empty? %>
    <% section.section_schedules.each do |section_schedule|%>
      <p>
        <%= section_schedule.weekday + ": " + prettyTime(Time.at(section_schedule.startTime)) + " to " + prettyTime(Time.at(section_schedule.endTime))%>
      </p>
    <% end %>
    <% else %>
      <p> No Schedule </p>
    <% end %>
  </div>
  <div class="col sub-section-section-edit">
    <p><%= link_to 'Show', section %></p>
    <p></p>
    
    <% if current_user.roles_name[0] == "admin"%>
      <%= link_to 'Edit', edit_section_path(section) %>
      <%= link_to 'Edit Schedule', '/sections/' + section.id.to_s + '/schedule_edit' %>
      <%= button_to "Delete", section_path(section), method: :delete %>
    <% end %>
  </div>
</div>
<% end %>

lab-3/app/views/courses/edit.html.erb
<div class="sub-course-edit-container">
	<div class="sub-course-edit-title">
		<h3>Course Edit</h3>
	</div>

<%= render 'form', course: @course %>
<div class = "sub-course-edit-all">
<p><%= link_to 'Show', @course %></p>
<p></p>
<p><%= link_to 'Back', courses_path %></p>
</div>
</div>

lab-3/app/views/courses/index.html.erb
<div class="sub-course-container">
  <div class="sub-course-title">
    <h3>Courses</h3>
  </div>
  <div class="filters">
  <%= render 'filterC' %>
  </div>
  <div class="row">
    <ul class="sub-course-board-nav">
      <li class="col sub-course-board-nav-course-number">Course Number</li>
      <li class="col sub-course-board-nav-course-name">Course Name</li>
      <li class="col sub-course-board-nav-course-graders">In Class Graders</li>
      <li class="col sub-course-board-nav-course-edit">View</li>
    </ul>
    <div class="col-9">

      <% @courses.each do |course| %>
      <div class="sub-course-board">
        <div class="col sub-course-course-number">
          CSE <%= course.courseNumber %>
        </div>
        <div class="col sub-course-course-name">
          <%= course.courseName %>
        </div>
        <div class="col sub-course-course-graders">
          <%= course.inClassGraders %>
        </div>
        <div class="col sub-course-course-edit">
          <p><%= link_to 'Show', course %></p>
          <% if current_user.roles_name[0] == "admin"%>
          <p><%= link_to 'Edit', edit_course_path(course) %></p>
          <p><%= button_to "Delete", course_path(course), method: :delete %></p>
          <% end %>
        </div>
      </div>
      <% end%>
      
    </div>
    	
    	<% if current_user.roles_name[0] == "admin"%>
    	<%= link_to 'New Course', new_course_path , :class => "link-btn"%>
    	
	<%= button_to 'Reload Database', 'courses/reload', method: :get, data: { confirm: "Are you sure?" }, :class => "link-btn" %>
	<% end %>
	</div>
	

lab-3/app/views/courses/new.html.erb
<div id="main-container">
<div id="class-list">

<h3>Creating New Course</h3>
<br>
<%= render 'form', course: @course %>

<%= link_to 'Back to Courses', courses_path %>

</div>
</div>

lab-3/app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>


<div class="sub-course-show-container">
  <div class="sub-course-title">
    <h3>Course Information</h3>
  </div>
  <div class="row">
    <ul class="sub-course-board-nav">
      <li class="col sub-course-board-nav-course-number">Course Number</li>
      <li class="col sub-course-board-nav-course-name">Course Name</li>
      <li class="col sub-course-board-nav-course-graders">In Class Graders</li>
      <li class="col sub-course-board-nav-course-edit">Edit</li>
    </ul>
    <div class="col-9">

      <div class="sub-course-board">
        <div class="col sub-course-course-number">
          <%= @course.courseNumber %>
        </div>
        <div class="col sub-course-course-name">
          <%= @course.courseName %>
        </div>
        <div class="col sub-course-course-graders">
          <%= @course.inClassGraders %>
        </div>
        <div class="col sub-course-course-edit">
          <% if current_user.roles_name[0] == "admin"%>
          <%= link_to 'Edit', edit_course_path(@course) %>
          <% end %>
          <%= link_to 'Back', courses_path %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="sub-course-show-container-two">
  <div class="sub-course-title">
    <h3>Available Sections</h3>
  </div>
  <div class="row">
    <ul class="sub-section-board-nav">
      <li class="col sub-section-board-nav-section-number">Section Number</li>
      <li class="col sub-section-board-nav-section-instructor">Instructor</li>
      <li class="col sub-section-board-nav-section-buliding">Location</li>
      <li class="col sub-section-board-nav-section-graders-need">Graders Assigned</li>
      <li class="col sub-section-board-nav-section-graders-need">Total Graders Needed</li>
      <li class="col sub-section-board-nav-section-section-schedule">Schedule</li>
      <li class="col sub-section-board-nav-section-edit">Edit</li>
    </ul>
	<%= render 'section_list' %>
  <a class="add-section-link" href="/sections/new?course=<%= @course_id %>">Add a Section</a>
</div>
	<%# This template will only render if the query course is a valid number %>
	<%# Course ID is needed to generate an Add Section link as we intend %>
	
</div>